.TH CLIENT 1 "September 2025" "v0.4.1" "User Commands"
.SH NAME
client \- simple client application for demonstrating dynamic library usage
.SH SYNOPSIS
.B client
[\fIoptions\fR]
.SH DESCRIPTION
The
.B client
program connects to the server and demonstrates the usage of functions
from the libmyutils shared library.

This program is part of the coursework project and showcases features such as:
- Using shared libraries
- Modular code design
- Basic client operations
.SH AUTHOR
Muhammad Zohaib <zohaib366tda@gmail.com>

